services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: homedesigndb
    environment:
      - SA_PASSWORD=StrongPass@123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d

  # --------------------------
  # MinIO Object Storage
  # --------------------------
  minio:
    image: minio/minio:latest
    container_name: homedesign_minio
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Web Console (MinIO Console)
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  minio_data:
